export const FETCHING_DATA = "FETCHING_DATA";
export const FETCH_GROSS_DATA = "FETCH_GROSS_DATA";
export const FETCH_COUNTRIES = "FETCH_COUNTRIES";
export const FETCH_DAILY_DATA = "FETCH_DAILY_DATA";
export const FETCH_COUNTRIES_AND_CODES = "FETCH_COUNTRIES_AND_CODES";
export const ADD_DEATH_DATA = "ADD_DEATH_DATA";
export const CHANGE_COUNTRY_CODE = "CHANGE_COUNTRY_CODE";
